<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

use Faker\Factory as Faker;

use Spatie\Permission\Models\Role;
use App\Models\TipoDocumento;
use App\Models\User;
use App\Models\Curso;
use App\Models\Matricula;
use App\Models\Alumno;
use Illuminate\Support\Facades\Hash;

class AlumnosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //


        DB::transaction(function () {
            $faker = Faker::create();
            $alumnos = [

                [ 'id' =>	0, 'primer_apellido' => "Asprilla", 'segundo_apellido' => "Grueso", 'primer_nombre' => "Mariangel", 'segundo_nombre' => "", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	0, 'primer_apellido' => "Castillo", 'segundo_apellido' => "Perea", 'primer_nombre' => "Zoe", 'segundo_nombre' => "", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	0, 'primer_apellido' => "García", 'segundo_apellido' => "Becerra", 'primer_nombre' => "Rafael", 'segundo_nombre' => "", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	0, 'primer_apellido' => "Martínez", 'segundo_apellido' => "Ruiz", 'primer_nombre' => "Jhoan", 'segundo_nombre' => "Alejandro", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	0, 'primer_apellido' => "Angulo", 'segundo_apellido' => "Landazury", 'primer_nombre' => "Zaily", 'segundo_nombre' => "Liseth", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	0, 'primer_apellido' => "Ferrin", 'segundo_apellido' => "Perea", 'primer_nombre' => "Valentino", 'segundo_nombre' => "", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	0, 'primer_apellido' => "Portacarrero", 'segundo_apellido' => "Muñoz", 'primer_nombre' => "Emily", 'segundo_nombre' => "Victoria", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	0, 'primer_apellido' => "Serna", 'segundo_apellido' => "Angulo", 'primer_nombre' => "Marco", 'segundo_nombre' => "José", 'grado' => "Jardín", 'curso' =>  "Jardín"],
                [ 'id' =>	20220000, 'primer_apellido' => "Angulo", 'segundo_apellido' => "Amu", 'primer_nombre' => "Gabriela", 'segundo_nombre' => "", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	20220001, 'primer_apellido' => "Caicedo", 'segundo_apellido' => "Martínez", 'primer_nombre' => "Alan", 'segundo_nombre' => "David", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Lozano", 'segundo_apellido' => "Arroyo", 'primer_nombre' => "Erick", 'segundo_nombre' => "Stevan", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Martínez", 'segundo_apellido' => "Farrin", 'primer_nombre' => "Hanna", 'segundo_nombre' => "Victoria", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	20230001, 'primer_apellido' => "González", 'segundo_apellido' => "Chavarriaga", 'primer_nombre' => "Samuel", 'segundo_nombre' => "Eduardo", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	20230002, 'primer_apellido' => "Guetara", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Liam", 'segundo_nombre' => "Jeremy", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	20230003, 'primer_apellido' => "Pinzón", 'segundo_apellido' => "Escamilla", 'primer_nombre' => "Rebecca", 'segundo_nombre' => "", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	20220004, 'primer_apellido' => "Reina", 'segundo_apellido' => "Miera", 'primer_nombre' => "Mila", 'segundo_nombre' => "Carolina", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Montaño", 'segundo_apellido' => "Orobio", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Felipe", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	20220003, 'primer_apellido' => "Zamora", 'segundo_apellido' => "Campo", 'primer_nombre' => "Eider", 'segundo_nombre' => "Samuel", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Pérez", 'segundo_apellido' => "Valois", 'primer_nombre' => "Salomé", 'segundo_nombre' => "", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Riascos", 'segundo_apellido' => "García", 'primer_nombre' => "Alexander", 'segundo_nombre' => "", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Rodríguez", 'segundo_apellido' => "Riascos", 'primer_nombre' => "Luciana", 'segundo_nombre' => "", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Valenzuela", 'segundo_apellido' => "Rodas", 'primer_nombre' => "Larry", 'segundo_nombre' => "Alexander", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	0, 'primer_apellido' => "Grisales", 'segundo_apellido' => "González", 'primer_nombre' => "Joaquín", 'segundo_nombre' => "", 'grado' => "Transición", 'curso' =>  "Transición"],
                [ 'id' =>	20220006, 'primer_apellido' => "Alomia", 'segundo_apellido' => "Montoya", 'primer_nombre' => "Carlos", 'segundo_nombre' => "Andrés", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20230004, 'primer_apellido' => "Angel", 'segundo_apellido' => "Zamora", 'primer_nombre' => "Juliana", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20230005, 'primer_apellido' => "Gamboa", 'segundo_apellido' => "Valverde", 'primer_nombre' => "Zoe", 'segundo_nombre' => "Johana", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Cierra", 'segundo_apellido' => "Anggel", 'primer_nombre' => "Yah", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20230007, 'primer_apellido' => "Hurtado", 'segundo_apellido' => "Arroyo", 'primer_nombre' => "Alana", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20220007, 'primer_apellido' => "López", 'segundo_apellido' => "Sánchez", 'primer_nombre' => "Alma", 'segundo_nombre' => "Gisell", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20230008, 'primer_apellido' => "Medina", 'segundo_apellido' => "Esquievel", 'primer_nombre' => "Emily", 'segundo_nombre' => "Sabrina", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Bello", 'segundo_apellido' => "Guerrero", 'primer_nombre' => "Jerónimo", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20230010, 'primer_apellido' => "Murillo", 'segundo_apellido' => "Mosquera", 'primer_nombre' => "Gabriela", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20220008, 'primer_apellido' => "Pasquel", 'segundo_apellido' => "Quiñones", 'primer_nombre' => "Carlos", 'segundo_nombre' => "Santiago", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Bonilla", 'segundo_apellido' => "Castro", 'primer_nombre' => "Miguel", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Bonilla", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Hanna", 'segundo_nombre' => "Isabella", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	20230013, 'primer_apellido' => "Vivas", 'segundo_apellido' => "Rivas", 'primer_nombre' => "Oriana", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Conde", 'segundo_apellido' => "Romero ", 'primer_nombre' => "Thomas", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Cano", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Mia", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Cortes", 'segundo_apellido' => "Cambindo", 'primer_nombre' => "Sammy ", 'segundo_nombre' => "Joel", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Debia", 'segundo_apellido' => "Estupiñan", 'primer_nombre' => "Juan", 'segundo_nombre' => "Sebastian", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Erazo", 'segundo_apellido' => "Reina", 'primer_nombre' => "Luciana", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Muñoz", 'segundo_apellido' => "Castaño", 'primer_nombre' => "Christopher", 'segundo_nombre' => "", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Palacios", 'segundo_apellido' => "Roobledo ", 'primer_nombre' => "Jose", 'segundo_nombre' => "Ivan", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Boya", 'segundo_apellido' => "Robledo", 'primer_nombre' => "Hans", 'segundo_nombre' => "Sabad", 'grado' => "Primero", 'curso' =>  "1"],
                [ 'id' =>	0, 'primer_apellido' => "Angulo", 'segundo_apellido' => "Dylan", 'primer_nombre' => "Andrés", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20220009, 'primer_apellido' => "Campaz", 'segundo_apellido' => "Burgos", 'primer_nombre' => "Ariana", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	0, 'primer_apellido' => "Hurtado", 'segundo_apellido' => "Velasques", 'primer_nombre' => "Miguel", 'segundo_nombre' => "Yair", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20210003, 'primer_apellido' => "Cuero", 'segundo_apellido' => "Murillo", 'primer_nombre' => "Juan", 'segundo_nombre' => "Diego", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230014, 'primer_apellido' => "Freire", 'segundo_apellido' => "Gomez", 'primer_nombre' => "Juan", 'segundo_nombre' => "Esteban", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230015, 'primer_apellido' => "Gamboa", 'segundo_apellido' => "Rengifo", 'primer_nombre' => "Genesis", 'segundo_nombre' => "Ariani", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20220010, 'primer_apellido' => "Gamboa", 'segundo_apellido' => "Sinisterra", 'primer_nombre' => "Didier", 'segundo_nombre' => "Ethan", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230016, 'primer_apellido' => "García", 'segundo_apellido' => "Guerra", 'primer_nombre' => "Valerie", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230017, 'primer_apellido' => "Herrera", 'segundo_apellido' => "Potes", 'primer_nombre' => "Tomás", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20210004, 'primer_apellido' => "Hurtado", 'segundo_apellido' => "Cabezas", 'primer_nombre' => "Joel", 'segundo_nombre' => "Benjamín", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230018, 'primer_apellido' => "Lobatón", 'segundo_apellido' => "Riascos", 'primer_nombre' => "Esteban", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230019, 'primer_apellido' => "Martínez", 'segundo_apellido' => "Henríquez", 'primer_nombre' => "Salome", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20220012, 'primer_apellido' => "Montaño", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230020, 'primer_apellido' => "Morales", 'segundo_apellido' => "Díaz", 'primer_nombre' => "Mateo", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230021, 'primer_apellido' => "Perea", 'segundo_apellido' => "Ruiz", 'primer_nombre' => "Joshua", 'segundo_nombre' => "David", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20210005, 'primer_apellido' => "Poso", 'segundo_apellido' => "Duque", 'primer_nombre' => "Salome", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	0, 'primer_apellido' => "Perea", 'segundo_apellido' => "Aragon", 'primer_nombre' => "Eysan", 'segundo_nombre' => "Maria", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230022, 'primer_apellido' => "Renteria", 'segundo_apellido' => "Torres", 'primer_nombre' => "Anahi", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230023, 'primer_apellido' => "Ruiz", 'segundo_apellido' => "Asprilla", 'primer_nombre' => "Lian", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230076, 'primer_apellido' => "Urrutia", 'segundo_apellido' => "Renteria", 'primer_nombre' => "Samuel", 'segundo_nombre' => "Steven", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230024, 'primer_apellido' => "Valencia", 'segundo_apellido' => "Turner", 'primer_nombre' => "Valery", 'segundo_nombre' => "Sophia", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20220015, 'primer_apellido' => "Vanegas", 'segundo_apellido' => "Ramírez", 'primer_nombre' => "Salome", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20230025, 'primer_apellido' => "Vera", 'segundo_apellido' => "Valenzuela", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20210006, 'primer_apellido' => "Zuluaga", 'segundo_apellido' => "Bohorquez", 'primer_nombre' => "Emmanuel", 'segundo_nombre' => "", 'grado' => "Segundo", 'curso' =>  "2"],
                [ 'id' =>	20220017, 'primer_apellido' => "Betancourt", 'segundo_apellido' => "Rodríguez", 'primer_nombre' => "Maria", 'segundo_nombre' => "Angel", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220019, 'primer_apellido' => "Figueroa", 'segundo_apellido' => "Tello", 'primer_nombre' => "Brandon", 'segundo_nombre' => "Nicolás", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	0, 'primer_apellido' => "Perez", 'segundo_apellido' => "Betancourt", 'primer_nombre' => "Santiago", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	0, 'primer_apellido' => "Garces", 'segundo_apellido' => "Álvarez", 'primer_nombre' => "Wilmar", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220021, 'primer_apellido' => "Gongora", 'segundo_apellido' => "Rosero", 'primer_nombre' => "Abraham", 'segundo_nombre' => "Samuel", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220023, 'primer_apellido' => "Grueso", 'segundo_apellido' => "Rentería", 'primer_nombre' => "Jerónimo", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220025, 'primer_apellido' => "Lozano", 'segundo_apellido' => "Rosero", 'primer_nombre' => "Sara", 'segundo_nombre' => "Sofía", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220026, 'primer_apellido' => "Martinez", 'segundo_apellido' => "González", 'primer_nombre' => "Luz", 'segundo_nombre' => "Victoria", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220028, 'primer_apellido' => "Martinez", 'segundo_apellido' => "Vergara", 'primer_nombre' => "Luciana", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220029, 'primer_apellido' => "Mina", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Lynette", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220031, 'primer_apellido' => "Mina", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Thiago", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	2020030, 'primer_apellido' => "Mosquera", 'segundo_apellido' => "Murillo", 'primer_nombre' => "Baily", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220032, 'primer_apellido' => "Muñoz", 'segundo_apellido' => "Vergara", 'primer_nombre' => "Mariana", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220034, 'primer_apellido' => "Obando", 'segundo_apellido' => "Gaviria", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220035, 'primer_apellido' => "Orobio", 'segundo_apellido' => "Sinisterra", 'primer_nombre' => "Juan", 'segundo_nombre' => "Diego", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220036, 'primer_apellido' => "Osorio", 'segundo_apellido' => "Sánchez", 'primer_nombre' => "Jerónimo", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220037, 'primer_apellido' => "Paz", 'segundo_apellido' => "Obando", 'primer_nombre' => "José", 'segundo_nombre' => "Martín", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220038, 'primer_apellido' => "Racines", 'segundo_apellido' => "Casierra", 'primer_nombre' => "Vladimir", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220039, 'primer_apellido' => "Saa ", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Dana ", 'segundo_nombre' => "Manuela", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220040, 'primer_apellido' => "Vente", 'segundo_apellido' => "Pretel", 'primer_nombre' => "Graciela", 'segundo_nombre' => "Rossana", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20220041, 'primer_apellido' => "Viafara", 'segundo_apellido' => "Ibarguen", 'primer_nombre' => "Carlos", 'segundo_nombre' => "Andres", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	0, 'primer_apellido' => "Rivera", 'segundo_apellido' => "Grueso", 'primer_nombre' => "Yeny", 'segundo_nombre' => "Nathalia", 'grado' => "Tercero", 'curso' =>  "3.2"],
                [ 'id' =>	20210007, 'primer_apellido' => "Anchico", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Sarah", 'segundo_nombre' => "Jeanette", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210009, 'primer_apellido' => "Banguera", 'segundo_apellido' => "Bolaños", 'primer_nombre' => "Jose", 'segundo_nombre' => "Luis", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20200007, 'primer_apellido' => "Bedoya", 'segundo_apellido' => "Buenaventura", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	0, 'primer_apellido' => "Camargo", 'segundo_apellido' => "Oliveros", 'primer_nombre' => "Amber", 'segundo_nombre' => "Luciana", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210011, 'primer_apellido' => "Díaz", 'segundo_apellido' => "Mejia", 'primer_nombre' => "Alejandro", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210010, 'primer_apellido' => "Díaz", 'segundo_apellido' => "Del Castillo", 'primer_nombre' => "Yasser", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210012, 'primer_apellido' => "Gómez", 'segundo_apellido' => "Gamboa", 'primer_nombre' => "Santiago", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210013, 'primer_apellido' => "Guapi", 'segundo_apellido' => "Estacio", 'primer_nombre' => "Adam", 'segundo_nombre' => "Sebastian", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20230026, 'primer_apellido' => "Mestrre", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Diana", 'segundo_nombre' => "Sara", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20190001, 'primer_apellido' => "Minota", 'segundo_apellido' => "Hurtado", 'primer_nombre' => "Nicolás", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	0, 'primer_apellido' => "Mina", 'segundo_apellido' => "Cambindo", 'primer_nombre' => "Dylan", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210014, 'primer_apellido' => "Muñoz", 'segundo_apellido' => "Arroyo", 'primer_nombre' => "Luis", 'segundo_nombre' => "Enrique", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20200010, 'primer_apellido' => "Obregon", 'segundo_apellido' => "Riascos", 'primer_nombre' => "Eblyn", 'segundo_nombre' => "Tatiana", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20200012, 'primer_apellido' => "Portocarrero", 'segundo_apellido' => "Ramirez", 'primer_nombre' => "Valeria", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20190067, 'primer_apellido' => "Riascos", 'segundo_apellido' => "Castro", 'primer_nombre' => "Samuel", 'segundo_nombre' => "Vladimir", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20230027, 'primer_apellido' => "Rivas", 'segundo_apellido' => "Diuza", 'primer_nombre' => "Anne", 'segundo_nombre' => "Valeria", 'grado' => "", 'curso' =>  "3.1"],
                [ 'id' =>	20210015, 'primer_apellido' => "Saavedra", 'segundo_apellido' => "Mondragon", 'primer_nombre' => "Nicolle", 'segundo_nombre' => "Jireh", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20190003, 'primer_apellido' => "Salas", 'segundo_apellido' => "Montilla", 'primer_nombre' => "Sebastián", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20220016, 'primer_apellido' => "Uran", 'segundo_apellido' => "Viveros", 'primer_nombre' => "Celeste", 'segundo_nombre' => "", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210016, 'primer_apellido' => "Vélez", 'segundo_apellido' => "Prado", 'primer_nombre' => "Paula", 'segundo_nombre' => "Andrea", 'grado' => "Tercero", 'curso' =>  "3.1"],
                [ 'id' =>	20210017, 'primer_apellido' => "Acosta", 'segundo_apellido' => "Saávedra", 'primer_nombre' => "Jhonatan", 'segundo_nombre' => "Esteban", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20220042, 'primer_apellido' => "Alomia", 'segundo_apellido' => "Montoya", 'primer_nombre' => "Elizabeth", 'segundo_nombre' => "Sofía", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20200015, 'primer_apellido' => "Areiza", 'segundo_apellido' => "Rengifo", 'primer_nombre' => "Daniel", 'segundo_nombre' => "Felipe", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20200016, 'primer_apellido' => "Areiza", 'segundo_apellido' => "Rengifo", 'primer_nombre' => "Juan", 'segundo_nombre' => "José", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	0, 'primer_apellido' => "Álvarez", 'segundo_apellido' => "Álvarez", 'primer_nombre' => "Aileen", 'segundo_nombre' => "Dahiana", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210018, 'primer_apellido' => "Bello", 'segundo_apellido' => "Guerrero", 'primer_nombre' => "Samuel", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210022, 'primer_apellido' => "Camacho", 'segundo_apellido' => "Hurtado", 'primer_nombre' => "Matías", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20230029, 'primer_apellido' => "Campiño", 'segundo_apellido' => "Cortés", 'primer_nombre' => "Emmanuel", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210019, 'primer_apellido' => "Carmona", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Laura", 'segundo_nombre' => "Daniela", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210020, 'primer_apellido' => "Castañeda", 'segundo_apellido' => "Paredes", 'primer_nombre' => "Dulce", 'segundo_nombre' => "María", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210021, 'primer_apellido' => "Castro", 'segundo_apellido' => "Dávila", 'primer_nombre' => "Joseph", 'segundo_nombre' => "Mathias", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210023, 'primer_apellido' => "Córdoba", 'segundo_apellido' => "Ibárguez", 'primer_nombre' => "Martín", 'segundo_nombre' => "Adrián", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20200018, 'primer_apellido' => "Foris", 'segundo_apellido' => "Cabezas", 'primer_nombre' => "María", 'segundo_nombre' => "Camila", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210025, 'primer_apellido' => "Granados", 'segundo_apellido' => "Rivera", 'primer_nombre' => "Julieta", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210027, 'primer_apellido' => "Morales", 'segundo_apellido' => "Rodríguez", 'primer_nombre' => "Salomé", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20200020, 'primer_apellido' => "Mosquera", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Hannah", 'segundo_nombre' => "Giuliana", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210028, 'primer_apellido' => "Mosquera", 'segundo_apellido' => "Cuero", 'primer_nombre' => "José", 'segundo_nombre' => "Alejandro", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210029, 'primer_apellido' => "Mosquera", 'segundo_apellido' => "Medranda", 'primer_nombre' => "Juan", 'segundo_nombre' => "José", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20220078, 'primer_apellido' => "Ochoa", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Antonella", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20190005, 'primer_apellido' => "Pastrana", 'segundo_apellido' => "Díaz", 'primer_nombre' => "Santiago", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210031, 'primer_apellido' => "Posso", 'segundo_apellido' => "Duque", 'primer_nombre' => "Luis", 'segundo_nombre' => "Alfonso", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20230030, 'primer_apellido' => "Tatis", 'segundo_apellido' => "Ballestas", 'primer_nombre' => "Juan", 'segundo_nombre' => "José", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	0, 'primer_apellido' => "Caicedo", 'segundo_apellido' => "Díaz", 'primer_nombre' => "Valerie", 'segundo_nombre' => "Sofía", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210032, 'primer_apellido' => "Vásquez", 'segundo_apellido' => "Osorio", 'primer_nombre' => "Celeste", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20210033, 'primer_apellido' => "Vinasco", 'segundo_apellido' => "Vergara", 'primer_nombre' => "José", 'segundo_nombre' => "Miguel", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20200025, 'primer_apellido' => "Zamora", 'segundo_apellido' => "Campo", 'primer_nombre' => "Dallana", 'segundo_nombre' => "Lizeth", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20220067, 'primer_apellido' => "Castillo", 'segundo_apellido' => "Perea", 'primer_nombre' => "Sarah", 'segundo_nombre' => "Sofía", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	0, 'primer_apellido' => "Gómez", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Felipe", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	0, 'primer_apellido' => "Sebastián", 'segundo_apellido' => "Montero", 'primer_nombre' => "Cruz", 'segundo_nombre' => "", 'grado' => "Cuarto", 'curso' =>  "4"],
                [ 'id' =>	20180004, 'primer_apellido' => "Alomia", 'segundo_apellido' => "Ortiz", 'primer_nombre' => "Hally", 'segundo_nombre' => "Sofí", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190060, 'primer_apellido' => "Campo", 'segundo_apellido' => "Estupinan", 'primer_nombre' => "Julian", 'segundo_nombre' => "David", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20200028, 'primer_apellido' => "Cardenas", 'segundo_apellido' => "Vergara", 'primer_nombre' => "Brian", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	2018005, 'primer_apellido' => "Castillo", 'segundo_apellido' => "Ramirez", 'primer_nombre' => "Alana", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190063, 'primer_apellido' => "Cortes", 'segundo_apellido' => "Tapias", 'primer_nombre' => "Luciana", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190065, 'primer_apellido' => "Gamboa", 'segundo_apellido' => "Valverde", 'primer_nombre' => "Manol", 'segundo_nombre' => "Andrei", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20200029, 'primer_apellido' => "Henao", 'segundo_apellido' => "Roldán", 'primer_nombre' => "Santiago", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190007, 'primer_apellido' => "Homez", 'segundo_apellido' => "Arias", 'primer_nombre' => "Ashley", 'segundo_nombre' => "Marian", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20220044, 'primer_apellido' => "Hurtado", 'segundo_apellido' => "Cabezas", 'primer_nombre' => "Leyla", 'segundo_nombre' => "Smantha", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190064, 'primer_apellido' => "Leal", 'segundo_apellido' => "Quiñones", 'primer_nombre' => "Roxana", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20200030, 'primer_apellido' => "Medina", 'segundo_apellido' => "Tobon", 'primer_nombre' => "Nathaly", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190009, 'primer_apellido' => "Naranjo", 'segundo_apellido' => "Rojas", 'primer_nombre' => "Nicolas", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20200031, 'primer_apellido' => "Ocoro", 'segundo_apellido' => "Diaz", 'primer_nombre' => "Juan", 'segundo_nombre' => "Jose", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190058, 'primer_apellido' => "Portocarrero", 'segundo_apellido' => "Muñoz", 'primer_nombre' => "Saira", 'segundo_nombre' => "Sofía", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20170001, 'primer_apellido' => "Quant", 'segundo_apellido' => "Rincón", 'primer_nombre' => "Zoe", 'segundo_nombre' => "Sophia", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20200032, 'primer_apellido' => "Ramirez", 'segundo_apellido' => "Rincón", 'primer_nombre' => "Martín", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20200033, 'primer_apellido' => "Renteria", 'segundo_apellido' => "Moreno", 'primer_nombre' => "Jesus", 'segundo_nombre' => "Ricardo", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20180007, 'primer_apellido' => "Riveros", 'segundo_apellido' => "Rengifo", 'primer_nombre' => "Pol", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20170003, 'primer_apellido' => "Tabares", 'segundo_apellido' => "Mosquera", 'primer_nombre' => "Mariana", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190062, 'primer_apellido' => "Valencia", 'segundo_apellido' => "Rios", 'primer_nombre' => "Leandro", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20180008, 'primer_apellido' => "Vanegas", 'segundo_apellido' => "Ramirez", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20190059, 'primer_apellido' => "Zuñiga", 'segundo_apellido' => "Hernández", 'primer_nombre' => "Dansha", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.1"],
                [ 'id' =>	20200034, 'primer_apellido' => "Arboleda", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Amy", 'segundo_nombre' => "Slene", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200037, 'primer_apellido' => "Caicedo", 'segundo_apellido' => "Molano", 'primer_nombre' => "Sarah", 'segundo_nombre' => "Julieth", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200038, 'primer_apellido' => "Calero", 'segundo_apellido' => "Mendez", 'primer_nombre' => "Valeria", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200039, 'primer_apellido' => "Campaz", 'segundo_apellido' => "Viafara", 'primer_nombre' => "Valery", 'segundo_nombre' => "Sofia", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200040, 'primer_apellido' => "Cardenas", 'segundo_apellido' => "Trilana", 'primer_nombre' => "Nikol", 'segundo_nombre' => "Sofia", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	0, 'primer_apellido' => "Díaz", 'segundo_apellido' => "Perea", 'primer_nombre' => "Laura", 'segundo_nombre' => "Sofía", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	0, 'primer_apellido' => "González", 'segundo_apellido' => "Nengeth", 'primer_nombre' => "Juan", 'segundo_nombre' => "Manuel", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200046, 'primer_apellido' => "Gomez", 'segundo_apellido' => "Aristizabal", 'primer_nombre' => "Isacc", 'segundo_nombre' => "Alejandro", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200047, 'primer_apellido' => "Gomez", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Mathias", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20230032, 'primer_apellido' => "Hinestroza", 'segundo_apellido' => "Mosquera", 'primer_nombre' => "Hernán", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200049, 'primer_apellido' => "Jimenez", 'segundo_apellido' => "Garcia", 'primer_nombre' => "Natalia", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200050, 'primer_apellido' => "Lemos", 'segundo_apellido' => "Chunga", 'primer_nombre' => "Valeri", 'segundo_nombre' => "Sofia", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200051, 'primer_apellido' => "Martinez", 'segundo_apellido' => "Gonzalez", 'primer_nombre' => "Said", 'segundo_nombre' => "David", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200052, 'primer_apellido' => "Moreno", 'segundo_apellido' => "Mora", 'primer_nombre' => "Juliana", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200053, 'primer_apellido' => "Ocampo", 'segundo_apellido' => "Florez", 'primer_nombre' => "Jeronimo", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200054, 'primer_apellido' => "Ordoñez", 'segundo_apellido' => "Salas", 'primer_nombre' => "Samantha", 'segundo_nombre' => "", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200058, 'primer_apellido' => "Solis", 'segundo_apellido' => "Gordillo", 'primer_nombre' => "Thael", 'segundo_nombre' => "Aynara", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20200059, 'primer_apellido' => "Valencia", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Vivica", 'segundo_nombre' => "Milena", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	0, 'primer_apellido' => "Morales", 'segundo_apellido' => "Gomez", 'primer_nombre' => "Juan", 'segundo_nombre' => "Sebastián", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	0, 'primer_apellido' => "Paredes", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Liz", 'segundo_nombre' => "Elaine", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	0, 'primer_apellido' => "Sinisterra", 'segundo_apellido' => "Sabi", 'primer_nombre' => "José", 'segundo_nombre' => "Daniel", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	0, 'primer_apellido' => "Joris", 'segundo_apellido' => "Moreno", 'primer_nombre' => "Omar", 'segundo_nombre' => "Fernando", 'grado' => "Quinto", 'curso' =>  "5.2"],
                [ 'id' =>	20180009, 'primer_apellido' => "Angulo", 'segundo_apellido' => "Ramirez", 'primer_nombre' => "Andres", 'segundo_nombre' => "Mauricio", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20230034, 'primer_apellido' => "Auz", 'segundo_apellido' => "Giraldo", 'primer_nombre' => "María", 'segundo_nombre' => "Camila", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190019, 'primer_apellido' => "Caicedo", 'segundo_apellido' => "Figueroa", 'primer_nombre' => "Johan", 'segundo_nombre' => "Andrés", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20170006, 'primer_apellido' => "Contreras", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Felipe", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190024, 'primer_apellido' => "Arias", 'segundo_apellido' => "Erazo", 'primer_nombre' => "Simon", 'segundo_nombre' => "Andres", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190012, 'primer_apellido' => "Franco", 'segundo_apellido' => "Campaz", 'primer_nombre' => "Dahia", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Áviles", 'segundo_apellido' => "Campaz", 'primer_nombre' => "Aria", 'segundo_nombre' => "Gabriela", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Castillo", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Valerie", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190013, 'primer_apellido' => "Hinestroza", 'segundo_apellido' => "Angulo", 'primer_nombre' => "Dilan", 'segundo_nombre' => "Samuel", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20230033, 'primer_apellido' => "Hinestroza", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Emily", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190020, 'primer_apellido' => "Hurtado", 'segundo_apellido' => "Arroyo", 'primer_nombre' => "Santiago", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190023, 'primer_apellido' => "Medina", 'segundo_apellido' => "Tobón", 'primer_nombre' => "Deisy", 'segundo_nombre' => "Andrea", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20230035, 'primer_apellido' => "Narvaez", 'segundo_apellido' => "Vega", 'primer_nombre' => "Siara", 'segundo_nombre' => "Valeria", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20180011, 'primer_apellido' => "Obregón", 'segundo_apellido' => "Riascos", 'primer_nombre' => "José", 'segundo_nombre' => "David", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190022, 'primer_apellido' => "Ortega", 'segundo_apellido' => "Micolta", 'primer_nombre' => "Joshua", 'segundo_nombre' => "Alejandro", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20230036, 'primer_apellido' => "Giraldo", 'segundo_apellido' => "Giraldo", 'primer_nombre' => "Andres", 'segundo_nombre' => "Felipe", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190008, 'primer_apellido' => "Hernández", 'segundo_apellido' => "Morán", 'primer_nombre' => "Xiana", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20180006, 'primer_apellido' => "Rivas", 'segundo_apellido' => "Cárdenas", 'primer_nombre' => "Santiago", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20200060, 'primer_apellido' => "Sepúlveda", 'segundo_apellido' => "Sánchez", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20190011, 'primer_apellido' => "Valencia", 'segundo_apellido' => "Casanova", 'primer_nombre' => "Valeria", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20180017, 'primer_apellido' => "Vallejo", 'segundo_apellido' => "Banguera", 'primer_nombre' => "Marlina", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Olaya", 'segundo_apellido' => "Preciado", 'primer_nombre' => "Sara", 'segundo_nombre' => "Nicol", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Quezada", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Delaney", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Ramírez", 'segundo_apellido' => "Márquez", 'primer_nombre' => "Samuel", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Ríos", 'segundo_apellido' => "Newball", 'primer_nombre' => "Linda", 'segundo_nombre' => "Sofía", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Suárez", 'segundo_apellido' => "Echeverry", 'primer_nombre' => "Mariand", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Van", 'segundo_apellido' => "Zapata", 'primer_nombre' => "Melian", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Vega", 'segundo_apellido' => "Bermúdez", 'primer_nombre' => "Nicolás", 'segundo_nombre' => "", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	0, 'primer_apellido' => "Sierra", 'segundo_apellido' => "Escudero", 'primer_nombre' => "Danner", 'segundo_nombre' => "Valentina", 'grado' => "Sexto", 'curso' =>  "6"],
                [ 'id' =>	20230037, 'primer_apellido' => "Aguilar", 'segundo_apellido' => "Meléndez", 'primer_nombre' => "Victoria", 'segundo_nombre' => "Alejandra", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20180031, 'primer_apellido' => "Amu", 'segundo_apellido' => "Garces", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Felipe", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20210038, 'primer_apellido' => "Angulo", 'segundo_apellido' => "Rojas", 'primer_nombre' => "Julián", 'segundo_nombre' => "Esteban", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230038, 'primer_apellido' => "Caicedo", 'segundo_apellido' => "Cundumi", 'primer_nombre' => "Lorena", 'segundo_nombre' => "Dahiana", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20190069, 'primer_apellido' => "Ceballos", 'segundo_apellido' => "Salguero", 'primer_nombre' => "Taliana", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20190072, 'primer_apellido' => "Murillo", 'segundo_apellido' => "Ramírez", 'primer_nombre' => "María", 'segundo_nombre' => "Paula", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20200062, 'primer_apellido' => "Palacios", 'segundo_apellido' => "Valenzuela", 'primer_nombre' => "Sara", 'segundo_nombre' => "Sofía", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230039, 'primer_apellido' => "Piedrahita", 'segundo_apellido' => "Riasco", 'primer_nombre' => "Brielen", 'segundo_nombre' => "Daniela", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	0, 'primer_apellido' => "López", 'segundo_apellido' => "Hernández", 'primer_nombre' => "Dulce", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230041, 'primer_apellido' => "Portocarrero", 'segundo_apellido' => "Viafara", 'primer_nombre' => "Florens", 'segundo_nombre' => "Lisbeth", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230042, 'primer_apellido' => "Quiñones", 'segundo_apellido' => "Arroyo", 'primer_nombre' => "David", 'segundo_nombre' => "Santiago", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20210039, 'primer_apellido' => "Rentería", 'segundo_apellido' => "Torres", 'primer_nombre' => "Emily", 'segundo_nombre' => "Diana", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230043, 'primer_apellido' => "Rios", 'segundo_apellido' => "Florez", 'primer_nombre' => "Zray", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20180029, 'primer_apellido' => "Rivas", 'segundo_apellido' => "Diuza", 'primer_nombre' => "José", 'segundo_nombre' => "Alexander", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230044, 'primer_apellido' => "Sánchez", 'segundo_apellido' => "Campaz", 'primer_nombre' => "Juan", 'segundo_nombre' => "Diego", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230045, 'primer_apellido' => "Sinisterra", 'segundo_apellido' => "Angulo", 'primer_nombre' => "Hillary", 'segundo_nombre' => "Fernanda", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230046, 'primer_apellido' => "Tatis", 'segundo_apellido' => "Ballestas", 'primer_nombre' => "Sofía", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230047, 'primer_apellido' => "Tejada", 'segundo_apellido' => "Moreira", 'primer_nombre' => "Samuel", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20200064, 'primer_apellido' => "Torres", 'segundo_apellido' => "Yaso", 'primer_nombre' => "Santiago", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20180048, 'primer_apellido' => "Vargas", 'segundo_apellido' => "Cardozo", 'primer_nombre' => "Wilson", 'segundo_nombre' => "Andrés", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20230048, 'primer_apellido' => "Vente", 'segundo_apellido' => "Pretel", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20190026, 'primer_apellido' => "Vidal", 'segundo_apellido' => "Rodríguez", 'primer_nombre' => "Kendra", 'segundo_nombre' => "Zharick", 'grado' => "Séptimo", 'curso' =>  "7.1"],
                [ 'id' =>	20180020, 'primer_apellido' => "Abadia", 'segundo_apellido' => "Arboleda", 'primer_nombre' => "Samuel", 'segundo_nombre' => "Andrés", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20230049, 'primer_apellido' => "Avendaño", 'segundo_apellido' => "Vascos", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20200066, 'primer_apellido' => "Caño", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Juan", 'segundo_nombre' => "Esteban", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20220046, 'primer_apellido' => "Chávez", 'segundo_apellido' => "Duque", 'primer_nombre' => "Juan", 'segundo_nombre' => "Manuel", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20170010, 'primer_apellido' => "Escobar", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Laura", 'segundo_nombre' => "Camila", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20230050, 'primer_apellido' => "Gámez", 'segundo_apellido' => "Caly", 'primer_nombre' => "Shaira", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20180024, 'primer_apellido' => "González", 'segundo_apellido' => "Angulo", 'primer_nombre' => "Maria", 'segundo_nombre' => "Camila", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20210041, 'primer_apellido' => "Jiménez", 'segundo_apellido' => "Arboleda", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20170014, 'primer_apellido' => "Jiménez", 'segundo_apellido' => "Sánchez", 'primer_nombre' => "Alán", 'segundo_nombre' => "Steven", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20230051, 'primer_apellido' => "López", 'segundo_apellido' => "Marín", 'primer_nombre' => "Juan", 'segundo_nombre' => "David", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20230052, 'primer_apellido' => "Luna", 'segundo_apellido' => "Díaz", 'primer_nombre' => "María", 'segundo_nombre' => "Paula", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20180027, 'primer_apellido' => "Montoya", 'segundo_apellido' => "Olmedo", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20230053, 'primer_apellido' => "Olaya", 'segundo_apellido' => "Angulo", 'primer_nombre' => "Iker", 'segundo_nombre' => "Balbino", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20160017, 'primer_apellido' => "Paredes", 'segundo_apellido' => "Paredes", 'primer_nombre' => "Juan", 'segundo_nombre' => "Alejandro", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20190029, 'primer_apellido' => "Perea", 'segundo_apellido' => "Prado", 'primer_nombre' => "Mariana", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20150045, 'primer_apellido' => "Riascos", 'segundo_apellido' => "Moreno", 'primer_nombre' => "Dylan", 'segundo_nombre' => "Santiago", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20180028, 'primer_apellido' => "Ríos", 'segundo_apellido' => "García", 'primer_nombre' => "Mia", 'segundo_nombre' => "Valentina", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20160016, 'primer_apellido' => "Salazar", 'segundo_apellido' => "Marin", 'primer_nombre' => "Sara", 'segundo_nombre' => "Marcela", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20160015, 'primer_apellido' => "Salazar", 'segundo_apellido' => "Valverde", 'primer_nombre' => "Juan", 'segundo_nombre' => "Dominick ", 'grado' => "", 'curso' =>  "7.2"],
                [ 'id' =>	20170012, 'primer_apellido' => "Sánchez", 'segundo_apellido' => "Ceballos", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	0, 'primer_apellido' => "Murillo", 'segundo_apellido' => "Granja", 'primer_nombre' => "Maria", 'segundo_nombre' => "Jose", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20180046, 'primer_apellido' => "Tobon", 'segundo_apellido' => "Montoya", 'primer_nombre' => "Hilary", 'segundo_nombre' => "", 'grado' => "Séptimo", 'curso' =>  "7.2"],
                [ 'id' =>	20230055, 'primer_apellido' => "Alegria", 'segundo_apellido' => "alencia", 'primer_nombre' => "Issi", 'segundo_nombre' => "Sofia", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170015, 'primer_apellido' => "Aristizabal", 'segundo_apellido' => "Ramírez", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Felipe", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20160021, 'primer_apellido' => "Arroyo", 'segundo_apellido' => "Estacio", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170025, 'primer_apellido' => "Castaño", 'segundo_apellido' => "García", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20200071, 'primer_apellido' => "Castaño", 'segundo_apellido' => "Mosquera", 'primer_nombre' => "Andres", 'segundo_nombre' => "Felipe", 'grado' => "", 'curso' =>  "8.1"],
                [ 'id' =>	20170027, 'primer_apellido' => "Cepeda", 'segundo_apellido' => "Henao", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Camilo", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20230054, 'primer_apellido' => "Garrido", 'segundo_apellido' => "Rodríguez", 'primer_nombre' => "Clara", 'segundo_nombre' => "Saraí", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170031, 'primer_apellido' => "Giraldo", 'segundo_apellido' => "Loaiza", 'primer_nombre' => "Emanuel", 'segundo_nombre' => "", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20150043, 'primer_apellido' => "Grueso", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "Ana", 'segundo_nombre' => "Gabriela", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20140004, 'primer_apellido' => "Guevara", 'segundo_apellido' => "Caicedo", 'primer_nombre' => "José", 'segundo_nombre' => "Leandro", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170033, 'primer_apellido' => "Muñoz", 'segundo_apellido' => "Arroyo", 'primer_nombre' => "Denzel", 'segundo_nombre' => "Enrique", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170034, 'primer_apellido' => "Muñoz", 'segundo_apellido' => "Castaño", 'primer_nombre' => "Camilo", 'segundo_nombre' => "Andrés", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170035, 'primer_apellido' => "Ocoro", 'segundo_apellido' => "Obregón", 'primer_nombre' => "Hanna", 'segundo_nombre' => "Isabella", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170018, 'primer_apellido' => "Ocoro", 'segundo_apellido' => "Obregón", 'primer_nombre' => "Aliria", 'segundo_nombre' => "José", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20230056, 'primer_apellido' => "Ocoro", 'segundo_apellido' => "Quiñones", 'primer_nombre' => "John", 'segundo_nombre' => "Edward", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170019, 'primer_apellido' => "Perez", 'segundo_apellido' => "Betancourt", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Felipe", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20170036, 'primer_apellido' => "Tello", 'segundo_apellido' => "Potes", 'primer_nombre' => "Arlam", 'segundo_nombre' => "Dayana", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20190030, 'primer_apellido' => "Vidal", 'segundo_apellido' => "Ruiz", 'primer_nombre' => "Samuel", 'segundo_nombre' => "", 'grado' => "Octavo", 'curso' =>  "8.1"],
                [ 'id' =>	20220047, 'primer_apellido' => "Arroyo", 'segundo_apellido' => "Micolta", 'primer_nombre' => "Camila", 'segundo_nombre' => "", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220048, 'primer_apellido' => "Fandiño", 'segundo_apellido' => "López", 'primer_nombre' => "Juan", 'segundo_nombre' => "Esteban", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220050, 'primer_apellido' => "Grueso", 'segundo_apellido' => "Montaño", 'primer_nombre' => "Manuel", 'segundo_nombre' => "Enrique", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220051, 'primer_apellido' => "Guzman", 'segundo_apellido' => "Salazar", 'primer_nombre' => "Melanie", 'segundo_nombre' => "Dayán", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220052, 'primer_apellido' => "Hurtado", 'segundo_apellido' => "Angulo", 'primer_nombre' => "Salma", 'segundo_nombre' => "Isabela", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220053, 'primer_apellido' => "Martínez", 'segundo_apellido' => "Mosquera", 'primer_nombre' => "Ely", 'segundo_nombre' => "Stephania", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220054, 'primer_apellido' => "Mendoza", 'segundo_apellido' => "Castaño", 'primer_nombre' => "Samuel", 'segundo_nombre' => "Andrés", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20230057, 'primer_apellido' => "Mestre", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Laura", 'segundo_nombre' => "Niroby", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220055, 'primer_apellido' => "Ramírez", 'segundo_apellido' => "Obregón", 'primer_nombre' => "Eiling", 'segundo_nombre' => "Aridna", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220056, 'primer_apellido' => "Reyna", 'segundo_apellido' => "Gámez", 'primer_nombre' => "Sara", 'segundo_nombre' => "", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220057, 'primer_apellido' => "Rincón", 'segundo_apellido' => "Payan", 'primer_nombre' => "Leslie", 'segundo_nombre' => "Gabriela", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220059, 'primer_apellido' => "Torres", 'segundo_apellido' => "Sinisterra", 'primer_nombre' => "Freddy", 'segundo_nombre' => "Michel", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220061, 'primer_apellido' => "Zapata", 'segundo_apellido' => "Díazgranados", 'primer_nombre' => "Jahan", 'segundo_nombre' => "", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220062, 'primer_apellido' => "Zapata", 'segundo_apellido' => "Montero", 'primer_nombre' => "Juan", 'segundo_nombre' => "Sebastián", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20220063, 'primer_apellido' => "Zapata", 'segundo_apellido' => "Valverde", 'primer_nombre' => "Juan", 'segundo_nombre' => "José", 'grado' => "Octavo", 'curso' =>  "8.2"],
                [ 'id' =>	20230059, 'primer_apellido' => "Anchico", 'segundo_apellido' => "Guerrero", 'primer_nombre' => "Isabel", 'segundo_nombre' => "Sofía", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20230060, 'primer_apellido' => "Andrade", 'segundo_apellido' => "Ramírez", 'primer_nombre' => "Malcolm", 'segundo_nombre' => "Ali", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20200080, 'primer_apellido' => "Areiza", 'segundo_apellido' => "Ledesma", 'primer_nombre' => "Samuel", 'segundo_nombre' => "", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20140000, 'primer_apellido' => "Bedoya", 'segundo_apellido' => "Hurtado", 'primer_nombre' => "Dama", 'segundo_nombre' => "Sofía", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20150018, 'primer_apellido' => "Bernat", 'segundo_apellido' => "Vargas", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20210045, 'primer_apellido' => "Cárdenas", 'segundo_apellido' => "Villa", 'primer_nombre' => "Meredith", 'segundo_nombre' => "Alaya", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20230058, 'primer_apellido' => "Cuero", 'segundo_apellido' => "Torres", 'primer_nombre' => "Joshua", 'segundo_nombre' => "", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20200112, 'primer_apellido' => "Duque", 'segundo_apellido' => "Guerrero", 'primer_nombre' => "Xcan", 'segundo_nombre' => "", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20190031, 'primer_apellido' => "Foris", 'segundo_apellido' => "Cabezas", 'primer_nombre' => "Nicolás", 'segundo_nombre' => "", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20230061, 'primer_apellido' => "Giraldo", 'segundo_apellido' => "Giraldo", 'primer_nombre' => "Lina", 'segundo_nombre' => "Lucía", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20160048, 'primer_apellido' => "Gómez", 'segundo_apellido' => "Gamboa", 'primer_nombre' => "Víctor", 'segundo_nombre' => "Danilo", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20160035, 'primer_apellido' => "González", 'segundo_apellido' => "Hinojoza", 'primer_nombre' => "Juan", 'segundo_nombre' => "Camilo", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20210048, 'primer_apellido' => "Gómez", 'segundo_apellido' => "Zuluaga", 'primer_nombre' => "Juan", 'segundo_nombre' => "Diego", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20200079, 'primer_apellido' => "Mina", 'segundo_apellido' => "Paz", 'primer_nombre' => "Tifra", 'segundo_nombre' => "Yisel", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20210049, 'primer_apellido' => "Mosquera", 'segundo_apellido' => "Cuero", 'primer_nombre' => "María", 'segundo_nombre' => "Paula", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20200078, 'primer_apellido' => "Naranjo", 'segundo_apellido' => "Rojas", 'primer_nombre' => "Manuel", 'segundo_nombre' => "Esteban", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20230074, 'primer_apellido' => "Pasquel", 'segundo_apellido' => "Quiñones", 'primer_nombre' => "Carlos", 'segundo_nombre' => "Andrés", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20150013, 'primer_apellido' => "Paz", 'segundo_apellido' => "Restrepo", 'primer_nombre' => "Samuel", 'segundo_nombre' => "David", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20190034, 'primer_apellido' => "Quiñones", 'segundo_apellido' => "Calonje", 'primer_nombre' => "Samuel", 'segundo_nombre' => "Felipe", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20200076, 'primer_apellido' => "Quiñones", 'segundo_apellido' => "Valencia", 'primer_nombre' => "María", 'segundo_nombre' => "José", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20170039, 'primer_apellido' => "Sánchez", 'segundo_apellido' => "Ceballos", 'primer_nombre' => "Sara", 'segundo_nombre' => "Camila", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20210057, 'primer_apellido' => "Torres", 'segundo_apellido' => "Cárdenas", 'primer_nombre' => "Louis", 'segundo_nombre' => "Anthony", 'grado' => "Noveno", 'curso' =>  "9"],
                [ 'id' =>	20130001, 'primer_apellido' => "Agudelo", 'segundo_apellido' => "López", 'primer_nombre' => "Elizabeth", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20150073, 'primer_apellido' => "Angulo", 'segundo_apellido' => "Marinez", 'primer_nombre' => "Samuel", 'segundo_nombre' => "Felipe", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20200082, 'primer_apellido' => "Angulo", 'segundo_apellido' => "Rojas", 'primer_nombre' => "Gabriela", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20200083, 'primer_apellido' => "Araujo", 'segundo_apellido' => "Moreno", 'primer_nombre' => "Andrés", 'segundo_nombre' => "Mauricio", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20150026, 'primer_apellido' => "Areiza", 'segundo_apellido' => "Rengifo", 'primer_nombre' => "Ana", 'segundo_nombre' => "Katalina", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20200084, 'primer_apellido' => "Balanta", 'segundo_apellido' => "Arroyo", 'primer_nombre' => "Christopher", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20170042, 'primer_apellido' => "Banguera", 'segundo_apellido' => "Bolaños", 'primer_nombre' => "Juan", 'segundo_nombre' => "Esteban", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20180058, 'primer_apellido' => "Calderon", 'segundo_apellido' => "Castro", 'primer_nombre' => "Karol", 'segundo_nombre' => "Eliant", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20200086, 'primer_apellido' => "Cambino", 'segundo_apellido' => "Batioja", 'primer_nombre' => "Danna", 'segundo_nombre' => "Saray", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20150027, 'primer_apellido' => "Cardona", 'segundo_apellido' => "Roldán", 'primer_nombre' => "Samuel", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20170041, 'primer_apellido' => "Castaño", 'segundo_apellido' => "García", 'primer_nombre' => "Valentina", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20180056, 'primer_apellido' => "Castrillon", 'segundo_apellido' => "Gutierrez", 'primer_nombre' => "Camilo", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20200087, 'primer_apellido' => "Ceballos", 'segundo_apellido' => "López", 'primer_nombre' => "Ángel", 'segundo_nombre' => "Elías", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20130003, 'primer_apellido' => "Contreras", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Rooney", 'segundo_nombre' => "Herman", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20150036, 'primer_apellido' => "Cordoba", 'segundo_apellido' => "Ibarguen", 'primer_nombre' => "Diana", 'segundo_nombre' => "Stil", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20140011, 'primer_apellido' => "Díaz", 'segundo_apellido' => "Perea", 'primer_nombre' => "María", 'segundo_nombre' => "Isabel", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20130011, 'primer_apellido' => "Minota", 'segundo_apellido' => "Hurtado", 'primer_nombre' => "Samuel", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20220065, 'primer_apellido' => "Murillo", 'segundo_apellido' => "Silva", 'primer_nombre' => "Edinson", 'segundo_nombre' => "Camilo", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20190037, 'primer_apellido' => "Ortega", 'segundo_apellido' => "Micolta", 'primer_nombre' => "Juan", 'segundo_nombre' => "Sebastián", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20230064, 'primer_apellido' => "Perlaza", 'segundo_apellido' => "Mina", 'primer_nombre' => "Sara", 'segundo_nombre' => "Valeria", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20200095, 'primer_apellido' => "Riovalles", 'segundo_apellido' => "Ceballos", 'primer_nombre' => "Sara", 'segundo_nombre' => "Cristina", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20150032, 'primer_apellido' => "Salazar ", 'segundo_apellido' => "Escamilla", 'primer_nombre' => "Isabella", 'segundo_nombre' => "", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20230065, 'primer_apellido' => "Turner", 'segundo_apellido' => "Estupiñan", 'primer_nombre' => "Sara", 'segundo_nombre' => "Nicole", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20150031, 'primer_apellido' => "Valencia", 'segundo_apellido' => "Duque", 'primer_nombre' => "Madisson", 'segundo_nombre' => "Angelica", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20200098, 'primer_apellido' => "Zapata", 'segundo_apellido' => "Oliver", 'primer_nombre' => "Joseph", 'segundo_nombre' => "Esteban", 'grado' => "Décimo", 'curso' =>  "10"],
                [ 'id' =>	20230066, 'primer_apellido' => "Arias", 'segundo_apellido' => "Becerra", 'primer_nombre' => "Julieth", 'segundo_nombre' => "", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20140025, 'primer_apellido' => "Bonilla", 'segundo_apellido' => "Quiñonez", 'primer_nombre' => "Thiago", 'segundo_nombre' => "Itan", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20230067, 'primer_apellido' => "Buenaventura", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Henry", 'segundo_nombre' => "Josue", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20220072, 'primer_apellido' => "Carmona", 'segundo_apellido' => "Valencia", 'primer_nombre' => "Hugo", 'segundo_nombre' => "Gabriel", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20130026, 'primer_apellido' => "Carrillo", 'segundo_apellido' => "González", 'primer_nombre' => "Sofía", 'segundo_nombre' => "", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20190048, 'primer_apellido' => "Castaño", 'segundo_apellido' => "Mosquera", 'primer_nombre' => "Diana", 'segundo_nombre' => "Camila", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20230069, 'primer_apellido' => "Celorio", 'segundo_apellido' => "Rivas", 'primer_nombre' => "Ronald", 'segundo_nombre' => "Steven", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20150049, 'primer_apellido' => "Estupinán", 'segundo_apellido' => "Reina", 'primer_nombre' => "Melody", 'segundo_nombre' => "Yorley", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20140023, 'primer_apellido' => "Garizado", 'segundo_apellido' => "Sánchez", 'primer_nombre' => "Salome", 'segundo_nombre' => "", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20130391, 'primer_apellido' => "Herman", 'segundo_apellido' => "Escobar", 'primer_nombre' => "María", 'segundo_nombre' => "Isabella", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20230070, 'primer_apellido' => "Hinestroza", 'segundo_apellido' => "Bonilla", 'primer_nombre' => "María", 'segundo_nombre' => "Alejandra", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20190043, 'primer_apellido' => "Morales", 'segundo_apellido' => "Diaz", 'primer_nombre' => "Luna", 'segundo_nombre' => "Daniel", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20130015, 'primer_apellido' => "Murillo", 'segundo_apellido' => "Marquez", 'primer_nombre' => "Eyleen", 'segundo_nombre' => "Johely", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20130020, 'primer_apellido' => "Murillo", 'segundo_apellido' => "Rojas", 'primer_nombre' => "Samuel", 'segundo_nombre' => "David", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20130019, 'primer_apellido' => "Nievas", 'segundo_apellido' => "Montes", 'primer_nombre' => "Mariana", 'segundo_nombre' => "", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20230071, 'primer_apellido' => "Palacios", 'segundo_apellido' => "Castillo", 'primer_nombre' => "Loorna", 'segundo_nombre' => "Stefanía", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20190041, 'primer_apellido' => "Quintero", 'segundo_apellido' => "Maturana", 'primer_nombre' => "Henny", 'segundo_nombre' => "Yuliana", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20200100, 'primer_apellido' => "Reina", 'segundo_apellido' => "Ibarguen", 'primer_nombre' => "William", 'segundo_nombre' => "Steven", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20220076, 'primer_apellido' => "Riascos", 'segundo_apellido' => "Barreiro", 'primer_nombre' => "Alexa", 'segundo_nombre' => "", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20130018, 'primer_apellido' => "Salazar", 'segundo_apellido' => "Marin", 'primer_nombre' => "Danna", 'segundo_nombre' => "Sofía", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20140019, 'primer_apellido' => "Sevilla", 'segundo_apellido' => "Camacho", 'primer_nombre' => "Ana", 'segundo_nombre' => "Sofía", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20150047, 'primer_apellido' => "Tobon", 'segundo_apellido' => "Tobon", 'primer_nombre' => "Jerónimo", 'segundo_nombre' => "", 'grado' => "Once", 'curso' =>  "11"],
                [ 'id' =>	20150048, 'primer_apellido' => "Tobon", 'segundo_apellido' => "Tobon", 'primer_nombre' => "Juan", 'segundo_nombre' => "José", 'grado' => "Once", 'curso' =>  "11"],            [ 'id' =>	20230072, 'primer_apellido' => "Urbano", 'segundo_apellido' => "Cuero", 'primer_nombre' => "Genesis", 'segundo_nombre' => "Fernanda", 'grado' => "Once", 'curso' =>  "11"],

            ];
            $role = Role::findByName('alumno', 'api');
            $tipodoc = TipoDocumento::where('nombre', 'Tarjeta de Identidad')->first();
            $matriculador = User::first();
            foreach ($alumnos as $alumno) {
                if($alumno['id']===0) {
                $alumno['id'] = Alumno::generarCodigo();
                }
                $curso = Curso::where('nombre', $alumno['curso'])->first();

                $user = User::create([
                    'primer_apellido' => $alumno['primer_apellido'],
                    'segundo_apellido' => $alumno['segundo_apellido'],
                    'primer_nombre' => $alumno['primer_nombre'],
                    'segundo_nombre' => $alumno['segundo_nombre'],
                    'celular' => $faker->phoneNumber,
                    'nid' => $alumno['id'],
                    'tipo_documento' => $tipodoc->id,
                    'email' => $faker->unique()->safeEmail,
                    'estado' => 'activo',
                    'email_verified_at' => now(),
                    'password' => Hash::make($alumno['id']),
                ]);
                $user->assignRole($role);

                $matricula = Matricula::create([
                    'curso' => $curso->id,
                    'alumno' => $user->id,
                    'matriculador' => $matriculador->id,
                    'estado' => 'activo'
                ]);
                $alumno = Alumno::create([
                    'id' => $user->id,
                    'codigo' =>  $alumno['id'],
                    'estado' => 'activo'
                ]);

            }
        }, 2);
    }
}

