<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Area;
use App\Models\Grado;
use App\Models\Materia;
class MateriasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $materias = [
            ["nombre" => "Aritmética", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Ciencias Naturales", "ih"=> 2, "porcentaje"=> 80, "area"=> "Ciencias Naturales", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 40, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Educación Sexual", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Español", "ih"=> 6, "porcentaje"=> 70, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Geografía", "ih"=> 4, "porcentaje"=> 100, "area"=> "Ciencias Sociales", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 2, "porcentaje"=> 30, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Música", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Primaria", "grado" => "Cuarto", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 40, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 2, "porcentaje"=> 30, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Integradas", "ih"=> 4, "porcentaje"=> 100, "area"=> "Integradas", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Lecto-escritura", "ih"=> 8, "porcentaje"=> 70, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Matemáticas", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Música", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 1, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Primaria", "grado" => "Primero", "estado"=>  "activo"],
            ["nombre" => "Aritmética", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Ciencias Naturales", "ih"=> 2, "porcentaje"=> 80, "area"=> "Ciencias Naturales", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 0, "porcentaje"=> 40, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Educación Sexual", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Español", "ih"=> 5, "porcentaje"=> 70, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Geografía", "ih"=> 4, "porcentaje"=> 100, "area"=> "Ciencias Sociales", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 2, "porcentaje"=> 30, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Música", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Primaria", "grado" => "Quinto", "estado"=>  "activo"],
            ["nombre" => "Aritmética", "ih"=> 8, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Castellano", "ih"=> 8, "porcentaje"=> 70, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Ciencias Naturales", "ih"=> 2, "porcentaje"=> 100, "area"=> "Ciencias Naturales", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 40, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 2, "porcentaje"=> 30, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Música", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 1, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Sociales", "ih"=> 2, "porcentaje"=> 100, "area"=> "Ciencias Sociales", "nivel" => "Básica Primaria", "grado" => "Segundo", "estado"=>  "activo"],
            ["nombre" => "Aritmética", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Ciencias Naturales", "ih"=> 2, "porcentaje"=> 80, "area"=> "Ciencias Naturales", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 40, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Educación Sexual", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Español", "ih"=> 6, "porcentaje"=> 70, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Geografía", "ih"=> 3, "porcentaje"=> 100, "area"=> "Ciencias Sociales", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 2, "porcentaje"=> 30, "area"=> "Humanidades", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Música", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Primaria", "grado" => "Tercero", "estado"=>  "activo"],
            ["nombre" => "algebra", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Biología", "ih"=> 3, "porcentaje"=> 60, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Caligrafía", "ih"=> 1, "porcentaje"=> 20, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Castellano", "ih"=> 5, "porcentaje"=> 60, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Contabilidad", "ih"=> 1, "porcentaje"=> 30, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 100, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Digitación de Textos", "ih"=> 1, "porcentaje"=> 30, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Filosofía", "ih"=> 1, "porcentaje"=> 15, "area"=> "Ciencias Sociales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Física", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Geografía", "ih"=> 4, "porcentaje"=> 85, "area"=> "Ciencias Sociales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 3, "porcentaje"=> 40, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Mentalidad Emprendedora", "ih"=> 1, "porcentaje"=> 20, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Química", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Secundaria", "grado" => "Noveno", "estado"=>  "activo"],
            ["nombre" => "algebra", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Caligrafía", "ih"=> 1, "porcentaje"=> 30, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Castellano", "ih"=> 6, "porcentaje"=> 60, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Ciencias Naturales", "ih"=> 3, "porcentaje"=> 60, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Contabilidad", "ih"=> 1, "porcentaje"=> 35, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 100, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 0, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Educación Sexual", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Física", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Geografía", "ih"=> 4, "porcentaje"=> 100, "area"=> "Ciencias Sociales", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 4, "porcentaje"=> 40, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Mentalidad Emprendedora", "ih"=> 1, "porcentaje"=> 35, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Secundaria", "grado" => "Octavo", "estado"=>  "activo"],
            ["nombre" => "Aritmética", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Caligrafía", "ih"=> 1, "porcentaje"=> 50, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Castellano", "ih"=> 6, "porcentaje"=> 60, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Ciencias Naturales", "ih"=> 3, "porcentaje"=> 70, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 40, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 0, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Geografía", "ih"=> 4, "porcentaje"=> 100, "area"=> "Ciencias Sociales", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 4, "porcentaje"=> 40, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Mentalidad Emprendedora", "ih"=> 1, "porcentaje"=> 50, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Música", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Orientación sexual", "ih"=> 1, "porcentaje"=> 30, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Secundaria", "grado" => "Séptimo", "estado"=>  "activo"],
            ["nombre" => "Aritmética", "ih"=> 6, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Biología", "ih"=> 3, "porcentaje"=> 70, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Caligrafía", "ih"=> 1, "porcentaje"=> 50, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 40, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 0, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Educación Sexual", "ih"=> 1, "porcentaje"=> 30, "area"=> "Ciencias Naturales", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Geografía", "ih"=> 4, "porcentaje"=> 100, "area"=> "Ciencias Sociales", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Informática", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 4, "porcentaje"=> 40, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Lengua Castellana", "ih"=> 6, "porcentaje"=> 60, "area"=> "Humanidades", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Mentalidad Emprendedora", "ih"=> 1, "porcentaje"=> 50, "area"=> "Comerciales", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Música", "ih"=> 1, "porcentaje"=> 30, "area"=> "Educación Artística", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Básica Secundaria", "grado" => "Sexto", "estado"=>  "activo"],
            ["nombre" => "Comercio Exterior", "ih"=> 1, "porcentaje"=> 15, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Comportamiento y Salud", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Contabilidad", "ih"=> 2, "porcentaje"=> 35, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 100, "area"=> "Educación Artística", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Español", "ih"=> 4, "porcentaje"=> 60, "area"=> "Humanidades", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Filosofía", "ih"=> 2, "porcentaje"=> 100, "area"=> "Filosofía", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Física", "ih"=> 4, "porcentaje"=> 40, "area"=> "Ciencias Naturales", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 3, "porcentaje"=> 40, "area"=> "Humanidades", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Mentalidad Emprendedora", "ih"=> 1, "porcentaje"=> 15, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Pool de Secretariado", "ih"=> 2, "porcentaje"=> 35, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Química", "ih"=> 4, "porcentaje"=> 40, "area"=> "Ciencias Naturales", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Trigonometría", "ih"=> 4, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Media", "grado" => "Décimo", "estado"=>  "activo"],
            ["nombre" => "Analisis", "ih"=> 3, "porcentaje"=> 100, "area"=> "Matemáticas", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Comercio Exterior", "ih"=> 2, "porcentaje"=> 26, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Comportamiento y Salud", "ih"=> 1, "porcentaje"=> 20, "area"=> "Ciencias Naturales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Contabilidad", "ih"=> 2, "porcentaje"=> 26, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Dibujo", "ih"=> 1, "porcentaje"=> 100, "area"=> "Educación Artística", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Disciplina", "ih"=> 1, "porcentaje"=> 100, "area"=> "Disciplina", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Economía", "ih"=> 1, "porcentaje"=> 12, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Español", "ih"=> 3, "porcentaje"=> 60, "area"=> "Humanidades", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Ética y Valores", "ih"=> 1, "porcentaje"=> 100, "area"=> "Ética y Valores", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Filosofía", "ih"=> 2, "porcentaje"=> 100, "area"=> "Filosofía", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Física", "ih"=> 4, "porcentaje"=> 40, "area"=> "Ciencias Naturales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 3, "porcentaje"=> 40, "area"=> "Humanidades", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Legislacion Comercial y Laboral", "ih"=> 1, "porcentaje"=> 12, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Mentalidad Emprendedora", "ih"=> 1, "porcentaje"=> 12, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Pool de Secretariado", "ih"=> 1, "porcentaje"=> 12, "area"=> "Comerciales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Química", "ih"=> 4, "porcentaje"=> 40, "area"=> "Ciencias Naturales", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Religión", "ih"=> 1, "porcentaje"=> 100, "area"=> "Religión", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Media", "grado" => "Once", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Artística", "nivel" => "Preescolar", "grado" => "Jardín", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Preescolar", "grado" => "Jardín", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 1, "porcentaje"=> 100, "area"=> "Inglés", "nivel" => "Preescolar", "grado" => "Jardín", "estado"=>  "activo"],
            ["nombre" => "Integradas", "ih"=> 3, "porcentaje"=> 100, "area"=> "Integradas", "nivel" => "Preescolar", "grado" => "Jardín", "estado"=>  "activo"],
            ["nombre" => "Matemáticas", "ih"=> 6, "porcentaje"=> 100, "area"=> "Pre-matemáticas", "nivel" => "Preescolar", "grado" => "Jardín", "estado"=>  "activo"],
            ["nombre" => "Pre-escritura", "ih"=> 5, "porcentaje"=> 100, "area"=> "Pre-escritura", "nivel" => "Preescolar", "grado" => "Jardín", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 1, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Preescolar", "grado" => "Jardín", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Artística", "nivel" => "Preescolar", "grado" => "Prejardín", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Preescolar", "grado" => "Prejardín", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 1, "porcentaje"=> 100, "area"=> "Inglés", "nivel" => "Preescolar", "grado" => "Prejardín", "estado"=>  "activo"],
            ["nombre" => "Integradas", "ih"=> 3, "porcentaje"=> 100, "area"=> "Integradas", "nivel" => "Preescolar", "grado" => "Prejardín", "estado"=>  "activo"],
            ["nombre" => "Matemáticas", "ih"=> 6, "porcentaje"=> 100, "area"=> "Pre-matemáticas", "nivel" => "Preescolar", "grado" => "Prejardín", "estado"=>  "activo"],
            ["nombre" => "Pre-escritura", "ih"=> 5, "porcentaje"=> 100, "area"=> "Pre-escritura", "nivel" => "Preescolar", "grado" => "Prejardín", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 1, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Preescolar", "grado" => "Prejardín", "estado"=>  "activo"],
            ["nombre" => "Danzas", "ih"=> 1, "porcentaje"=> 100, "area"=> "Educación Artística", "nivel" => "Preescolar", "grado" => "Transición", "estado"=>  "activo"],
            ["nombre" => "Educación Física", "ih"=> 2, "porcentaje"=> 100, "area"=> "Educación Física Recreación y Deportes", "nivel" => "Preescolar", "grado" => "Transición", "estado"=>  "activo"],
            ["nombre" => "Inglés", "ih"=> 1, "porcentaje"=> 30, "area"=> "Pre-escritura", "nivel" => "Preescolar", "grado" => "Transición", "estado"=>  "activo"],
            ["nombre" => "Integradas", "ih"=> 3, "porcentaje"=> 100, "area"=> "Integradas", "nivel" => "Preescolar", "grado" => "Transición", "estado"=>  "activo"],
            ["nombre" => "Matemáticas", "ih"=> 5, "porcentaje"=> 100, "area"=> "Pre-matemáticas", "nivel" => "Preescolar", "grado" => "Transición", "estado"=>  "activo"],
            ["nombre" => "Pre-escritura", "ih"=> 7, "porcentaje"=> 70, "area"=> "Pre-escritura", "nivel" => "Preescolar", "grado" => "Transición", "estado"=>  "activo"],
            ["nombre" => "Sistemas", "ih"=> 1, "porcentaje"=> 100, "area"=> "Informática", "nivel" => "Preescolar", "grado" => "Transición", "estado"=>  "activo"],
            // Añade más materias según sea necesario
        ];

        foreach ($materias as $materia) {
            $areaId = Area::where('nombre', $materia['area'])->first()->id;
            //var_dump($materia['area'].' '.$materia['nombre'].' '.$materia['grado']);
            $gradoId = Grado::where('nombre', $materia['grado'])->first()->id;
            Materia::create([
                'nombre' => $materia['nombre'],
                'ih' => $materia['ih'],
                'estado' => $materia['estado'],
                'grado' => $gradoId,
                'area' => $areaId,
                'porcentaje' => $materia['porcentaje'],
                // Asegúrate de generar un UUID si tu modelo no lo hace automáticamente
            ]);
        }
    }
}
